### ISSUE TITLE
UnboundLocalError: local variable 'controllers' referenced before assignment

### ISSUE THREAD

**Issue by andreypolyak** [volshebniks/sauresha#13]
Иногда получаю в логе вот такую ошибку, видимо из-за того, что не удается загрузить данные из облака Сауреса

```
2021-06-30 16:07:20 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sauresha/sensor.py", line 298, in refresh
    self.update()
  File "/config/custom_components/sauresha/sensor.py", line 344, in update
    self._state = self.fetch_state()
  File "/config/custom_components/sauresha/sensor.py", line 312, in fetch_state
    my_controller = self.current_controller_info
  File "/config/custom_components/sauresha/sensor.py", line 266, in current_controller_info
    return self.controller.get_controller(self.flat_id, self.serial_number)
  File "/config/custom_components/sauresha/sauresha.py", line 113, in get_controller
    controllers = self.get_controllers(flat_id)
  File "/config/custom_components/sauresha/sauresha.py", line 105, in get_controllers
    self._sensors = controllers
UnboundLocalError: local variable 'controllers' referenced before assignment
```

Конфиг:
```YAML
- platform: sauresha
  email: !secret sensor_saures_email
  password: !secret sensor_saures_password
  flat_id: !secret sensor_saures_flat_id
  controllers:
    !secret sensor_saures_controller_sn_electricity:
      name: saures_electricity
    !secret sensor_saures_controller_sn_water:
      name: saures_water
  counters:
    !secret sensor_saures_counter_sn_cold:
      name: cold_water
    !secret sensor_saures_counter_sn_hot:
      name: hot_water
    !secret sensor_saures_counter_sn_electricity:
      name: electricity
  scan_interval:
    minutes: 60
```

Версия компонента: 0.6.1
Версия HA: 2021.6.6

**Comment by volshebniks** [comment]
Да про эту оцибку я знаю. Как будет время - сделаю обработку ошибки. На рабоспособности это никак не сказывается.

**Comment by volshebniks** [comment]
исправлено в версии 1.0 -    на данный момент ставиться только из ветки master
