### ISSUE TITLE
AttributeError: 'NodeListClass' object has no attribute 'items'

### ISSUE THREAD

**Issue by V-A-S** [volshebniks/sauresha#14]
Ошибка возникает при старте HA и, как следствие, далее с интерграцией ничего не происходит независимо от того, что прописано (или, наоборот, не прописано) в конфигах
```2021-07-12 11:46:10 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up sauresha platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sauresha/sensor.py", line 91, in setup_platform
    for key, value in conf_counters.items():
AttributeError: 'NodeListClass' object has no attribute 'items'

Версия компонента 0.6.1 (установлен через HACS)
Версия ХА 2021.7.1

**Comment by V-A-S** [comment]
misconfig

**Comment by slm2000** [comment]
так в чем ошибка конфига была? у меня такая же

**Comment by volshebniks** [comment]
а настройки сделаны согласно иинстуркции? -  было большое изменение формата настроек.
