### ISSUE TITLE
Error doing job: Future exception was never retrieved

### ISSUE THREAD

**Issue by neKola-ru** [volshebniks/sauresha#17]
Hello, when I install "flat: 0", then everything is fine, but the description indicates how to get flat
ID flat: *********, Алексеева, 115 : 13520

When I install "flat: 13520", then everything collapses. prescribe flat:0 ?

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sauresha/sensor.py", line 298, in refresh
    self.update()
  File "/config/custom_components/sauresha/sensor.py", line 344, in update
    self._state = self.fetch_state()
  File "/config/custom_components/sauresha/sensor.py", line 312, in fetch_state
    my_controller = self.current_controller_info
  File "/config/custom_components/sauresha/sensor.py", line 266, in current_controller_info
    return self.controller.get_controller(self.flat_id, self.serial_number)
  File "/config/custom_components/sauresha/sauresha.py", line 113, in get_controller
    controllers = self.get_controllers(flat_id)
  File "/config/custom_components/sauresha/sauresha.py", line 105, in get_controllers
    self._sensors = controllers
UnboundLocalError: local variable 'controllers' referenced before assignment

**Comment by volshebniks** [comment]
This is duplication of known issue
