### ISSUE TITLE
Error adding entities for domain sensor with platform sauresha

### ISSUE THREAD

**Issue by dobriys** [volshebniks/sauresha#25]
Вот такое в логах и сенсоры хол и гор воды не появляются. Сам контроллер нормально 

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:569 
Integration: Sensor (documentation, issues) 
First occurred: 11:06:22 (2 occurrences) 
Last logged: 11:06:23

Error adding entities for domain sensor with platform sauresha
Error while setting up sauresha platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 569, in _async_add_entity
    raise HomeAssistantError(f"Invalid entity ID: {entity.entity_id}")
homeassistant.exceptions.HomeAssistantError: Invalid entity ID: sensor.sauresha_
```

**Comment by dobriys** [comment]
убрал в настройках сенсоров из имени сенсоров кириллицу и всё заработало.
Так не работало:
```
- platform: sauresha
  email: email
  password: paswword
  flat_id: 01234 
  controllers:
    FFFFFFFFFFFF
      name: Saures
  counters:
    12345:
      name: Холдная
    67890:
      name: Горячая
  scan_interval:
    minutes: 60
```

Так работает:
```
- platform: sauresha
  email: email
  password: paswword
  flat_id: 01234 
  controllers:
    FFFFFFFFFFFF
      name: Saures
  counters:
    12345:
      name: cold
    67890:
      name: hot
  scan_interval:
    minutes: 60 
```
