### ISSUE TITLE
Ошибки создания устройств типа binary_sensor и switch

### ISSUE THREAD

**Issue by Gimlir** [volshebniks/sauresha#29]
Тестирую на версии из ветки master по состоянию на https://github.com/volshebniks/sauresha/commit/8642a44227ab5c7b016e927f76e11ce3e9a9e0cf

Интеграцию установил, вбил логин и пароль через GUI. 
После первого рестарта HA интеграция нашла квартиру и все устройства, но не все смогла создать как объекты в HA.
```
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Scan_interval = 1:00:00
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Scan_interval = 1:00:00
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Scan_interval = 1:00:00
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Scan_interval = 1:00:00
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Scan_interval = 1:00:00
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Scan_interval = 1:00:00
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Scan_interval = 1:00:00
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Scan_interval = 1:00:00
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Scan_interval = 1:00:00
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Start meter_id: 14488
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Finish meter_id: 14488
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Start meter_id: 14489
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Finish meter_id: 14489
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Start meter_id: 14490
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Finish meter_id: 14490
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Start sn: 4245208
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Finish sn: 4245208
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Start meter_id: 14486
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Finish meter_id: 14486
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Start meter_id: 14487
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Finish meter_id: 14487
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Start meter_id: 14492
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Finish meter_id: 14492
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Start meter_id: 14493
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Finish meter_id: 14493
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Start meter_id: 14491
2022-06-03 13:26:39 WARNING (MainThread) [custom_components.sauresha.entity] Update Finish meter_id: 14491
2022-06-03 13:26:39 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform sauresha
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 534, in _async_add_entity
entity.entity_id = entry.entity_id
AttributeError: can't set attribute
2022-06-03 13:26:39 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform sauresha
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 534, in _async_add_entity
entity.entity_id = entry.entity_id
AttributeError: can't set attribute
2022-06-03 13:26:39 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up sauresha platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 534, in _async_add_entity
entity.entity_id = entry.entity_id
AttributeError: can't set attribute
2022-06-03 13:26:39 ERROR (MainThread) [homeassistant.components.switch] Error while setting up sauresha platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 534, in _async_add_entity
entity.entity_id = entry.entity_id
AttributeError: can't set attribute
``` 
канал управления краном и каналы датчиков протечки видны как отсутствующие
![image](https://user-images.githubusercontent.com/39776670/171840607-d02e85c9-efb5-4901-bdcd-200af74e38db.png)
![image](https://user-images.githubusercontent.com/39776670/171840652-86f53ebb-dea5-4554-abfc-9e9793e991d4.png)
![image](https://user-images.githubusercontent.com/39776670/171840682-d3d24818-b8bb-4a6e-adc2-46291b65bc5e.png)
![image](https://user-images.githubusercontent.com/39776670/171840874-af75a266-9b40-4039-9c35-55ddcfd818bb.png)
Сам контроллер saures создался как сенсор вообще без какого-либо имени.

**Comment by volshebniks** [comment]
поправил в ветке master, 
контролер без имени - поому что оно не задано в личном кабинете.  в следующем обновлении поправлю  - что бы было хотят какое то

**Comment by Gimlir** [comment]
Работает, спасибо!
